server:
  port: 2333
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
  output:
    ansi:
      enabled: always
lavalink:
  plugins:
    - dependency: "me.rohank05:lavalink-filter-plugin:0.0.1"
      repository: "https://jitpack.io/"
    - dependency: "com.github.TopiSenpai.LavaSrc:lavasrc-plugin:3.1.7"
      repository: "https://jitpack.io/"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5"
    - dependency: "dev.schlaubi.lyrics:lavalink:2.5.0"
    - dependency: "com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1"
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    opusEncodingQuality: 5 
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000 
    useSeekGhosting: true 
    youtubePlaylistLoadLimit: 9
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
logging:
  level:
    root: INFO
    lavalink: INFO
plugins:
  youtube:
    enabled: true 
    allowSearch: true 
    allowDirectVideoIds: true 
    allowDirectPlaylistIds: true 
    oauth:
      enabled: true
      # refreshToken:
      skipInitialization: true
    clients:
      - MUSIC
      - WEB
      - MWEB
      - WEBEMBEDDED 
      - ANDROID_MUSIC 
      - TV
      - TVHTML5EMBEDDED
  lavasrc:
    providers:
      - "dzsearch:%QUERY%"
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%" 
    sources:
      spotify: true
      applemusic: true 
      deezer: true 
    spotify:
      # clientId:
      # clientSecret:
      countryCode: "US" 
      playlistLoadLimit: 6 
      albumLoadLimit: 6 
      resolveArtistsInSearch: true 
      localFiles: false 
    deezer:
      # masterDecryptionKey: 
      formats: [ "FLAC", "MP3_320", "MP3_256", "MP3_128", "MP3_64", "AAC_64" ] 
  lyrics:
    countryCode: us
